baseURL = 'https://mattbrocklehurst.co.uk'
languageCode = 'en-gb'
title = 'Matt Brocklehurst | Systems Surgeon' # This fixes the tab title
theme = 'terminal'

[params]
  # These are specific to the Terminal theme
  contentTypeName = "none"
  title = "Matt Brocklehurst"
  subtitle = "R&D Systems Architect & Problem Liquidator"
  owner = "Matt Brocklehurst"
  
  # This section handles the "Terminal" appearance
  [params.terminal]
    showTitle = true
    showSubtitle = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1  # Lowest weight = First position
  [[menu.main]]
    identifier = "missions"
    name = "The Missions"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mattbrocklehurst"
    weight = 20
